#!/bin/zsh

if [[ -z $MIND_ROOT ]]; then
        echo '$MIND_ROOT not set!' >/dev/stderr
        exit 1
fi
source $MIND_ROOT/scripts/config.sh
cd $MIND_ROOT/scripts

if [[ $# -ne 4 ]]; then
        echo "cn, fh, bs, lmem_mib"
        exit 1
fi

cnthreads=$1
fhthreads=$2
bs=$3
local_mem_mib=$4

log_root='/tmp/logs'

local n_threads=$fhthreads

output_log="$log_root/$n_threads.log"
pre_log="$log_root/pre.$n_threads.log"
post_log="$log_root/post.$n_threads.log"
pre_hwcounter_log="$log_root/pre.hwcounter.$n_threads.log"
post_hwcounter_log="$log_root/post.hwcounter.$n_threads.log"

mkdir -p $log_root

psample 0
echo "test-one: generating post-test logfiles"
date +%s > $post_hwcounter_log
sudo ethtool -S $cn_nic &>>$post_hwcounter_log

dmesg --color=always -w &> $post_log &
local dmesg_pid=$!
pprint
sleep 3s
kill $dmesg_pid
wait $dmesg_pid

sync $pre_log $post_log $pre_hwcounter_log $post_hwcounter_log

perf_data="$log_root/$n_threads.perf.data"
folded_stacks="$log_root/$n_threads.perf.folded"
flamegraph_svg="$log_root/$n_threads.flamegraph.svg"
perf_report="$log_root/$n_threads.perf.report.txt"
if [[ -f $perf_data ]]; then
	$MIND_ROOT/mind_linux/tools/perf/perf buildid-cache --add $MIND_ROOT/mind_linux/roce_modules/roce4disagg.ko
	$MIND_ROOT/mind_linux/tools/perf/perf script -i $perf_data \
		| /home/mage/FlameGraph/stackcollapse-perf.pl \
		> $folded_stacks
	/home/mage/FlameGraph/flamegraph.pl $folded_stacks \
		> $flamegraph_svg
	$MIND_ROOT/mind_linux/tools/perf/perf report -i $perf_data --stdio \
		> $perf_report
	sync $perf_data $folded_stacks $flamegraph_svg $perf_report
fi
